### ISSUE TITLE
Option to keep mini-map in normal position when in vehicle

### ISSUE THREAD

**Issue by raineday** [Wutname1/SpartanUI#138]
Wondering if you would be able to implement an option to keep the map in the center of the screen for people who have mini-map addon's I use sexymap and would like an option to keep the map in the main location of SUI when i enter vehicle mode. I don't have the map module enabled and I've never had an issue with the map going to the center of the screen that others have had.

**Comment by Wutname1** [comment]
What skin are you using?

**Comment by raineday** [comment]
using the classic skin

**Comment by Kamear** [comment]
I use the classic skin also. I never changed the default setting for the vehicle ui however whenever I entered a vehicle the minimap moved to the top center of the screen. That was the worst place for it because it was in the way. Wutname1 moved it to the top right which is now out of the way so I'm ok with that. But I was thinking the same thing about leaving it in the default position where it normally is. It didn't appear to me that it would block anything by leaving it there but all vehicles might not look the same so I'm not sure.

**Comment by bizzy401** [comment]
Would it be possible to make the minimap draggable with alt click while in vehicles? Just a thought.
