### ISSUE TITLE
 Huge FPS drop right after initial loading

### ISSUE THREAD

**Issue by gustavolrcoelho** [Wutname1/SpartanUI#18]
Hi, I have an FX6300 with an 1050Ti and 16Gb of ram and I run the game at 1080p@80fps avg.
I used SpartanUi back in Cata and it had an annoying problem that it dropped the FPS a lot right after the loading, like, to 1FPS for a few seconds, but back then I used a notebook and thought it was because of that, so I switched to ElvUI and had no issues.
Last week, I decided to move back because I really enjoy the graphics and the target positioning, but I am having the same issue now. What gives? Why does my fps gets as low as 1FPS after loading, but then after some 15~20 seconds it goes back to normal (60~100fps, depending on the xpac) and never drops again?

https://youtu.be/tPTb3AjbrHg

**Comment by Wutname1** [comment]
Looks like you are having some bad texture pop-in issues as well. Are you running on a SSD or standard Hard drive? SpartanUI should not care but a cheap $40 SSD in general will help alot with that.  

As to why SpartanUI could be contributing to it. I saw you have FuBar at the bottom and SpartanUI is "snapping" up to account for it. Could you try to disable all the addons other than Bartender4 and SpartanUI?

I will also say SpartanUI's code is not optimized right now. I am working on standardizing the code and cleaning it up right now for the BFA version, and that should help get some better performance out of it. Over the years things have gotten messy since i dont always have time to "do it right" and with the [Pateron](https://patreon.com/SpartanUI) I am finally able to justify spending the time to do a cleanup.

**Comment by Wutname1** [comment]
Make sure you turn off SpartanUI Animated as well since it is not part of this download.

**Comment by gustavolrcoelho** [comment]
What do you mean? I am not using FuBar. That is Titan Panel.
About the drive, it is a common HDD.

**Comment by Wutname1** [comment]
The skin looked like a FuBar Skin. either way spartanui is accounting for that and adjusting the art. try disabling the other addons and see if the issue is still there.

**Comment by gustavolrcoelho** [comment]
Hey, tried disabling the titan bar and still had the issue. Any other test?

**Comment by Wutname1** [comment]
Did you do just Titan bar or all other add-ons?

**Comment by gustavolrcoelho** [comment]
Only TP. The rest of my addons are only QoL, like AutoTurnIn, Bagnon, etc. Other UI addons should not interfere, once they are specific to some interactions.

**Comment by Wutname1** [comment]
They can easily still interfere like issue #7 was not SpartanUI causing the issue but a compatibility issue with AuctionMaster. 

> AutoTurnIn
SpartanUI has a autoturn in module it woun't cause the load issues you are seeing but that is one example of a possible interference unless you disable the autoturnin module of SUI

**Comment by gustavolrcoelho** [comment]
Hey, I updated all my software and I did not see any fps drop ATM. Will let you know if this solved the issue.

**Comment by gustavolrcoelho** [comment]
The problem persists. I will test it on the weekend, disabling and enabling each addon to see what happens.

**Comment by Wutname1** [comment]
Instead of going through all of them one at a time disable everything other than SUI and Bartender4 first.

**Comment by Wutname1** [comment]
Still an issue with the new updates to SUI, BT4, and WoW?

**Comment by gustavolrcoelho** [comment]
Sorry bro, completely forgot about it, will do it as soon as I can get online

**Comment by gustavolrcoelho** [comment]
Well, all my adons are having errors, even those that I updated. This might take a while.

**Comment by gustavolrcoelho** [comment]
Well, disabled all addons and enabled only SUI and still had frame drops as well as some bugs with the buff and debuff icons not showing properly, the player bar floating at the wrong height and some others. Will back up from the SUI for now and check it later on :/
