### ISSUE TITLE
LUA errors

### ISSUE THREAD

**Issue by Whatsatotem** [Wutname1/SpartanUI#193]
![LUAall](https://user-images.githubusercontent.com/41389109/62687687-e4ff3000-b98c-11e9-9a17-79811e2e0b32.png)

i have no clue how many of these are relevant, but they all popped up while playing with the new 5.2.0 beta nameplates

**Comment by Whatsatotem** [comment]
![WoWScrnShot_080819_030551](https://user-images.githubusercontent.com/41389109/62688212-057bba00-b98e-11e9-968f-f6baa5fa765e.jpg)

this ones the one that somehow got deleted

**Comment by Whatsatotem** [comment]
![WoWScrnShot_080819_030648](https://user-images.githubusercontent.com/41389109/62688265-217f5b80-b98e-11e9-9e53-4727baafbef7.jpg)

this ones the one that got deleted somehow

**Comment by Wutname1** [comment]
Few of those are player frame errors that will be solved by 6.0.... few are a result of other issues. Let me know how the new build treats you.

Due to the Anchor point bug you will need to manually fix your DB by running this:

`/script SUI.DBMod.NamePlates.elements.SUI_ClassIcon.position={}`

or do a /suihelp > reset profile.
