### ISSUE TITLE
Tons of Errors and Missing UI Elements in Classic

### ISSUE THREAD

**Issue by shytamir** [Wutname1/SpartanUI#206]
After installing the latest update (5.2.4) it seems the UI broke on my wow classic client. It's throwing massive amounts of errors, and bartender and the graphic elements are failing to position correctly. I've reverted to the previous version (5.2.3) and everything works again.

**Comment by Whatsatotem** [comment]
![image](https://user-images.githubusercontent.com/41389109/64003426-d8748000-cad1-11e9-8b57-93574c4837dd.png)

figured if ima post it anywhere might as well be an existing post lol

**Comment by Solithan** [comment]
It's the same on BfA.

**Comment by ZippityDoodah** [comment]
Ever since I updated to 5.2.4 in WoW Classic it began throwing errors, wasn't loading properly, and the command line to load the settings did nothing... As soon as I went back one version (to 5.2.3) everything worked fine again... Not sure if this has something to do with 5.2.4 or if it had anything to do with WoW Classic also installing a tiny patch last night...

**Comment by Wutname1** [comment]
Fixed. in new update. Sorry everyone. this was the issue... 
![image](https://user-images.githubusercontent.com/704321/64034442-4b9ee600-cb14-11e9-8541-91187764b6fc.png)
1 letter.
