### ISSUE TITLE
Target Bar Display

### ISSUE THREAD

**Issue by gtdrgn2002** [Wutname1/SpartanUI#232]
The Target bar in WoW Classic shows up with hit points and mana as a total of 100, this happens with each player or NPC that is targeted. I checked to see if it was a level dependent p[ropblem and it happened with all elevels targeted.

**Comment by Wutname1** [comment]
This is by design. 

Via discord FAQ. Q5. Why does everything have 100 health?
A. Classic did not have exact health numbers ***#nochanges***. Some addons do show you health numbers by doing the math for you (you hit the target for 50 and did X% of dmg). This is planned to be built into SpartanUI in 6.0. As of SUI 5.2.8 'Real Mob Health' is now supported and can be installed separately.
