### ISSUE TITLE
Classic - Action Bars - Enable for right hand side?

### ISSUE THREAD

**Issue by MidnightJay** [Wutname1/SpartanUI#234]
Is there any way to add the action bars on the right hand side?  I've looked and it doesn't appear to be an option that I can find anywhere.

Any help would be appreciated.

Thanks!

**Comment by Wutname1** [comment]
Do you mean on the side of your screen? SUI moves all of them to the bottom

**Comment by MidnightJay** [comment]
Correct, I like the UI as is but the wife was curious if there was a way to have them on the right hand side (as the basic UI has).

Thanks.

**Comment by rfahey79** [comment]
The action bars are handled by bartender, you can enable extra bars and configure them how you like. by default, SUI uses action bars 1-6. So 7-10 you can put wherever you'd like. for the classic vertical action bars look, just adjust the bar width to 1.

**Comment by MidnightJay** [comment]
Awesome, thanks!

**Comment by Shaanea** [comment]
hallo :) came here with the same wish - added actionbar 7 for my hunter
and it works great - place enough for the great amount of hunterskills now - and
it was automatically there for my twinks too - but except for Mages, Warlock and Pala
these bars are used for changing stances and/or forms

  7 | Druid Cat Form/Rogue Stealth/Warrior Battle Stance/Priest Shadowform
  8 | Warrior Defensive Stance/Rogue Shadow Dance
  9 | Druid Bear Form/Warrior Berserker Stance
10 | Druid Moonkin Form

my problem is now to find a way to individualize the settings in bartender working with SpartanUI so I can use different actionbars with my other chars and their classes

Any idea or help would be appreciated
Thanks

**Comment by MidnightJay** [comment]
Hello,

Those functions work fine for me, the action bars change for me on the
warrior with each stance, same for druid and the stealth pops up fine on a
rogue.  Now Spriest the action bar doesn't change and never has even in
vanilla... .spriest get gimmped that way.

But have no issues with action bars changing as needed.

Sorry can't be of any help.

Good luck

**Comment by Shaanea** [comment]
Hello J

 

Thank you for your quick answer. I’m from Germany, so excuse me if my english isn’t always perfect. ;)

 

I guess I made my problems not clear enough for you to understand.

 

This is a Link to a picture of my Hunter‘s SpartanUi: http://heidi-roessner.de/wp-content/uploads/2020/07/shaanea_spartanui.jpg

 

As you can see, on the left hand side oft he picture, I activated an addional taks bar via Bartender for her to get enough place for all the needed Hunterspells ingame, flasks etc.

 

When I did this in Bartender, it automatically aktivated this bar for all my twinks what I didn’t  realized until I played them.

 

So I looked for a possibilty to individualize the bartender settings by char but I didn’t found a possibily for checking this in the settings.

 

Hope I could explain it better this time.

BTW I’m a big Fan on SpartanUI since years, in WoW Retail anyway.

 

Have a great time

 

Shaanea

 

Von: MidnightJay [mailto:notifications@github.com] 
Gesendet: Mittwoch, 22. Juli 2020 19:05
An: Wutname1/SpartanUI
Cc: Shaanea; Comment
Betreff: Re: [Wutname1/SpartanUI] Classic - Action Bars - Enable for right hand side? (#234)

 

Hello,

Those functions work fine for me, the action bars change for me on the
warrior with each stance, same for druid and the stealth pops up fine on a
rogue. Now Spriest the action bar doesn't change and never has even in
vanilla... .spriest get gimmped that way.

But have no issues with action bars changing as needed.

Sorry can't be of any help.

Good luck

**Comment by MidnightJay** [comment]
Hello,

The picture helped explain perfectly.  I was in Germany last August
although I'm sure things are much different now, I still have some sweet
mustard!

This is for bartender and not for SpartanUI, open up bartender and you
should see a profile tab, select that and create the profile with the extra
action bar for your twink, you can either then create a default one for
none twinks or create a profile for each character, up to you:

[image: image.png]

Hope this helps.

I didn't create Bartender or SpartanUI, just a user of both.  Good luck!

**Comment by MidnightJay** [comment]
Hello,

Can you share what you enabled to the extra toolbar?  I've tried many
variations and can't get it to work for some reason.  I'm sure it's just a
box or something I'm not checking.  Any help would be great!

Thanks.

**Comment by Shaanea** [comment]
Hello,

 

 

Sorry for late answer.

 

There was not really something to enable, activate a bar, make a unique bartender profile for the char. SpartanUi  asks then if you want allow this and reloads. 


Sometimes SpartanUi resets settings then – next time you log in, you sometimes have and activate the chosen bar again, but saved with the active self made profile in bartender it works then and SpartanUi never asks again.

 

Hope this will help

 

thanks

 

 

 

Von: MidnightJay [mailto:notifications@github.com] 
Gesendet: Donnerstag, 30. Juli 2020 13:56
An: Wutname1/SpartanUI
Cc: Shaanea; Comment
Betreff: Re: [Wutname1/SpartanUI] Classic - Action Bars - Enable for right hand side? (#234)

 

Hello,

Can you share what you enabled to the extra toolbar? I've tried many
variations and can't get it to work for some reason. I'm sure it's just a
box or something I'm not checking. Any help would be great!

Thanks.
