### ISSUE TITLE
[Classic] Party/Raid Frames don't always update properly, or on time

### ISSUE THREAD

**Issue by karai17** [Wutname1/SpartanUI#265]
I've noticed this a lot recently. I think it may happen when I am in combat and some event occurs that should update unit frames. For example:

* When a new member is added to the party, their unit frame won't show up until I `/reload`
* Sometimes when a party is converted into a raid, it does not hide the party frames until I `/reload`
* If a player has gone AFK or returned from AFK, the AFK status marker on theri portrait is not toggled unless I click the unit frame or `/reload`

An aside, I've also noticed that the unit frames for any unit seem to be fairly slow at updating combat information, such as HP. I'll stab something and it will take far longer than reasonable for their HP to change. This has caused me a lot of panic during intense pulls where I am spamming my heals as fast as possible and the tank's HP doesn't move. My first thought when I noticed this was "The tank is taking about as much damage as I am helaing, so it looks like no change is happening" but that doesn't seem to be the case. Instead, it seems that the unit frames lag behind by several frames.

**Comment by Wutname1** [comment]
> When a new member is added to the party, their unit frame won't show up until I /reload
> Sometimes when a party is converted into a raid, it does not hide the party frames until I /reload

Known issue this is due the the graphical nature of SUI and the changes blizz has made over the years. SUI 6.0 is in alpha right now and unitframes have been rebuilt from scratch to address this issues as well as many others.

> An aside, I've also noticed that the unit frames for any unit seem to be fairly slow at updating combat information, such as HP. I'll stab something and it will take far longer than reasonable for their HP to change.

Part of this is classic seems to update in less frequent chunks, there are a few optimizations in 6.0 and in the unit frame backend systems but you will still see this slightly if you are paying very close attention on classic. The issue is not there in retail leading me to lean toward its just another classic #nochanges thing.
