### ISSUE TITLE
Player Frame missing.

### ISSUE THREAD

**Issue by Khiswow** [Wutname1/SpartanUI#286]
Hi, I tried 2/3 different layouts and for each of them, the player's (and target) one is missing. Instead I have a simple box with my portait next to a large health bar and a small ressource one.

Plus, with the previous built the extra bar (the one used for sanity in visions) is missing,

I use the last one uploaded today on Curse (5.3 - Sui 5.9.9 Build 681) and tried to reset my profile.

**Comment by Wutname1** [comment]
Build 681 is SUI 5.9.9 (Otherwise known as SUI 6.0 Alpha)

It is NOT SUI 5.3 the SUI 5.2.X and 5.3.X are completely diffrent version of SUI as 5.9.9 is a full rewrite of the addon. 

Please make sure LUA errors are on:
> Turn on  LUA errors with '/console scriptErrors 1'
> Once errors are on you can /reload and see if any errors popup
> If you get more than 1 error i would recommend installing Bugsack and Bug grabber.
> BugSack - https://www.curseforge.com/wow/addons/bugsack
> BugGrabber -  https://www.curseforge.com/wow/addons/bug-grabber
> These will put the errors into a bag icon on your minimap and make them less annoying.

For SUI alpha issues it is best to use Discord if possible. Please ensure errors are enabled and see if you get any if so please post them here. If you do not get any errors reset your SUI database via /suihelp

**Comment by Wutname1** [comment]
If you were on the SUI Alpha builds and updated to 5.3 then again back to the Alpha builds there is a chance 5.3 corrupted your database and resetting it & bartender will resolve most of the issues.

**Comment by Khiswow** [comment]
I must have switched to the alpha by error with the twitch client. Installing 5.3 and resetting the UI solved everything. Thanks.
