### ISSUE TITLE
QOL addon sell button to market window

### ISSUE THREAD

**Issue by Maimah** [Wutname1/SpartanUI#68]
When I run multiple old raids and I've got spartan set to sell anything under ilevel blah (which is awesome thank you!) it only sells a portion before panicking and stopping XD only way to restart it is to close the store window and reopen it to pop again. Not a huge OH NOES IS BROKEN just a "hey this would be easier if there was a sell button on that window to restart it"

**Comment by Wutname1** [comment]
As of the last update a new slider was introduced on the Auto sell page that allows you to sell more than the default of five items per bag when you open the window. This is a temporary solution, just know that the higher you increase this number the more likely that you could cause a bag error. it's not a big issue but it can really mess up your bags until you reload the ui or relaunch the game. As sometimes wow gets confused on what it sold and what didn't if too many things sell to quick. 

To your suggestion: Rather than add a button what I was thinking is adding a timer/delay between the 5 item batches. That way you still get the same thing that you're looking for (not having to close and reopen the window) without having to click a button.

**Comment by Maimah** [comment]
sounds like a plan!
